import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApiProvider, Web3Provider } from "@allo/kit";

import "@allo/kit/styles.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApiProvider>
        <Web3Provider>
          <body className={inter.className}>{children}</body>
        </Web3Provider>
      </ApiProvider>
    </html>
  );
}
